name: Generate Tweets JSON

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 0-15/3 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data
        uses: actions/checkout@v2

      - name: Checkout cmd
        uses: actions/checkout@v2
        with:
          repository: uakihir0/gallery-cmd
          ref: main
          path: cmd
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install TensorFlow
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow
          pip install numpy
          pip install keras
          pip install Pillow

      - name: Move json
        run: |
          cp ./gallery.json ./cmd/work/gallery.json

      - name: Exec cmd
        run: |
          cd ./cmd && ./gradlew bootRun

      - name: Move json
        run: |
          cp ./cmd/work/gallery.json ./gallery.json

      - name: Change Cron Schedule
        run: |
          sed -i -e "5s|.*|    - cron: '$(($RANDOM % 60)) 0-15/3 * * *'|g" ./.github/workflows/build.yml
          rm -f ./.github/workflows/*.yml-e

      - name: Push
        run: |
          git config --global user.email "bot.a.urusihara@gmail.com"
          git config --global user.name "Akihiro Urushihara (bot)"
          git add gallery.json
          git add .github/workflows/build.yml
          git commit -m "by GitHub Action CI (SHA ${GITHUB_SHA})"
          git push origin main
